@startuml
'https://plantuml.com/activity-diagram-beta

start
split
    :array;
split again
    :lower_index;
split again
    :higher_index;
end split
if (lower_index == higher_index) then (yes)
    :return array;
    stop
else
    :mid = (hi - li)/2 + li;
    :left_hi = mid\nright_li = mid + 1;
    fork
        split
            :array;
        split again
            :lower_index;
        split again
            :left_hi;
        end split
        start
        :return left_array;
    fork again
        split
            :array;
        split again
            :right_li;
        split again
            :higher_index;
        end split
        start
        :return right_array;
    end fork
    :result_i = 0;
    repeat
        if (left_i == left_max) then (yes)
            repeat
                :result_array[result_i] = right_array[right_i];
                :right_i++\nresult_i++;
            repeat while(right_i < right_max)
            :return result_array;
            stop
        else if (right_i == right_max) then (yes)
            repeat
                :result_array[result_i] = left_array[left_i];
                :left_i++\nresult_i++;
            repeat while(left_i < left_max)
            :return result_array;
            stop
        endif

        if (left_array[left_i] <= (right_array[right_i]) then (yes)
            :result_array[result_i] = left_array[left_i];
            :left_i++;
        else (no)
            :result_array[result_i] = right_array[righ_i];
            :right_i++;
        endif
        :result_i++;
    repeat while(left_i < left_max\nor\nright_i < right_max)
endif

stop

@enduml
